# Generated by Django 4.2.7 on 2023-11-24 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="appeal",
            name="sentiment",
            field=models.TextField(default=""),
        ),
    ]
