# Generated by Django 4.2.7 on 2023-11-24 14:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("web", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="appeal",
            name="date",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
