# Generated by Django 4.2.7 on 2023-11-24 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0002_appeal_sentiment"),
    ]

    operations = [
        migrations.AddField(
            model_name="appeal",
            name="location",
            field=models.TextField(default=""),
        ),
        migrations.AddField(
            model_name="appeal",
            name="organisation",
            field=models.TextField(default=""),
        ),
        migrations.AddField(
            model_name="appeal",
            name="person",
            field=models.TextField(default=""),
        ),
    ]
