# Generated by Django 4.2.7 on 2023-11-24 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0003_appeal_location_appeal_organisation_appeal_person"),
    ]

    operations = [
        migrations.RenameField(
            model_name="appeal",
            old_name="organisation",
            new_name="organization",
        ),
    ]
