# Generated by Django 4.2.7 on 2023-11-24 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0004_rename_organisation_appeal_organization"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="appeal",
            name="location",
        ),
        migrations.RemoveField(
            model_name="appeal",
            name="organization",
        ),
        migrations.RemoveField(
            model_name="appeal",
            name="person",
        ),
    ]
