# Generated by Django 4.2.7 on 2023-11-24 16:01

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("web", "0002_alter_appeal_date"),
        (
            "web",
            "0005_remove_appeal_location_remove_appeal_organization_and_more",
        ),
    ]

    operations = []
